export {default as HomePage} from "./HomePage/HomePage"
export {default as BookInfo} from "./BookInfo/BookInfo"
export {default as Korzina} from "./Korzina/Korzina"
export {default as LoginPage} from "./LoginPage/LoginPage"
export {default as SiginIn} from "./SiginIn/SiginIn"
export {default as CategoryBook} from "./CategoryBook/CategoryBook"
export {default as Profil} from "./Profil/Profil"
export {default as Favorite} from "./Favorite/Favorite"
export {default as Order} from "./Order/Order"
export {default as Search } from "./Search/Search"
